### ISSUE TITLE
Improve output for handle two formats

### ISSUE THREAD

**Issue by vcobis-avio** [avioconsulting/mule-linter#105]
Add support for both outputs so we can still see console output while generating JSON for Sonar as well like (CONSOLE + JSON).

**Comment by manikmagar** [comment]
@adesjardin  @vcobis-avio  I can think of 3 options for this one - 

**Option 1**: Allow multiple formats to be configured in the plugin configuration. [_Breaks the compatibility if the current version is released as v1_.]
```
<configuration>
	<formats>
            <format>CONSOLE</format>
            <format>JSON</format>
        </formats>
</configuration>
```
**Option 2**: The plugin will output CONSOLE always, in addition to any format added in configuration.  The following config will write to the console and also generate JSON format. To skip JSON,  don't include any format tag or set it to CONSOLE. [_Plugin options are maintained but new behavior of always writing to CONSOLE_]
```
<configuration>
	<appDir>${basedir}</appDir>
	<ruleConfiguration>${basedir}/AVIOCustomRuleConfiguration.groovy</ruleConfiguration>
	<outputDirectory>${project.build.directory}/reports</outputDirectory>
	<format>JSON</format>
</configuration>
```

**Option 3:** Generate CONSOLE and JSON always. Format tag not needed unless more formats (eg. XML) are supported.
