### ISSUE TITLE
Keeping mule-linter-core.gdsl updated

### ISSUE THREAD

**Issue by manikmagar** [avioconsulting/mule-linter#111]
The Gradle build will generate `mule-linter-core.gdsl` file during the build. When any rules are modified or added, this regenerated file must be committed back to the repository. This will ensure that [intellij auto-completion ](https://github.com/avioconsulting/mule-linter#using-intellij-auto-completion) is always up to date. To avoid forgetting to commit this file, Github Actions workflow should check for the dirtiness of this file during build workflow. If the file is dirty w.r.t head, the build should fail. This can give a chance to review and fix the updates.

**Comment by adesjardin** [comment]
This was fixed by removing the gdsl from source control and fixing the generation location to be the build location and not src.  The latest gdsl is built as part of the CI process and included in the release jar.
