### ISSUE TITLE
chore(build): deploy core rules documentation to github pages

### ISSUE THREAD

**Issue by manikmagar** [avioconsulting/mule-linter#133]
Mule Linter core is shipped with [many rules](https://github.com/avioconsulting/mule-linter/tree/main/mule-linter-core/src/main/groovy/com/avioconsulting/mule/linter/rule). When building the module, groovy docs are generated under `./mule-linter-core/build/docs`. It will be helpful to publish these to github pages for reference. It was attempted in branch `feat/github-pages-deploy` but needs to be reviewed. 

Similar was done for OTEL repo - https://github.com/avioconsulting/mule-opentelemetry-module/blob/main/.github/workflows/github-pages.yml.

**Comment by dileepkumarv-avio** [comment]
Updated github action to deploy gradle docs to github pages. This has been implemented in the PR - [#135](https://github.com/avioconsulting/mule-linter/pull/135)
