### ISSUE TITLE
CICD Rule to look for a GitHub Actions workflow

### ISSUE THREAD

**Issue by kkingavio** [avioconsulting/mule-linter#145]
Github actions have yaml files (at least one) typically named build.yaml 

These files exist in .github/workflows/build.yaml

**Comment by manikmagar** [comment]
@kkingavio @adesjardin Linter rule #172 for gitlab file was contributed and we are targeting it for 1.2.0 release. I think we could add this one too and target together. Quick thought, should we instead just add a simple FILE_EXISTS rule that checks for existence of given file path? Github build file names may be customized, there is no fixed name as per Github. There are conventions, such as build.yml but not always.

**Comment by adesjardin** [comment]
Yes, I think a common file exists rule would be good, in theory the gitlab rule, pom rule, azure devops, and even this one if we implement it should all just extend that rule with a default value for the file then.

**Comment by manikmagar** [comment]
@adesjardin #175  adds capabilities to check for files with the given path. That should take care of this issue.

```
FILE_EXISTS {
  path = '.github/workflows/my-custom-build.yml'
}
```
