### ISSUE TITLE
PomDependencyVersion

### ISSUE THREAD

**Issue by thedevnisarg** [avioconsulting/mule-linter#39]
Must be able to validate specified dependency (_groupId, artifactId_) with its version.
- Must be able to locate and parse an application and find the pom.xml file
- Must be able to compare groupId, artifactId, version to specified value.
- Throw error if values does not match or found in dependency.
- Support greater then or equal to version as well

<dependencies>
        <dependency>
            <groupId>**org.mule.connectors**</groupId>
            <artifactId>**mule-http-connector**</artifactId>
            <version>**1.5.11**</version>
            <classifier>mule-plugin</classifier>
        </dependency>
        <dependency>
            <groupId>org.mule.connectors</groupId>
            <artifactId>mule-sockets-connector</artifactId>
            <version>1.1.5</version>
            <classifier>mule-plugin</classifier>
        </dependency>
</dependencies>

**Comment by MrMcCartney** [comment]
Should be resolved by PR #51
