### ISSUE TITLE
Added API Autodiscovery Rule for Mule Applications with HTTP Listener/ APIKIT Router

### ISSUE THREAD

**Issue by swapnavenugopal** [avioconsulting/mule-linter#76]
API Autodiscovery is critical Rule from  API Security perspective. 
Without API Auto discovery configuration no security policy can be applied via API Manager.
This Rule majorly checks for the below configuration:

- Every flow in the Mule application with a HTTP listener component, should have an API Autodiscovery configuration for it where _`flowRef`_ attribute matches the name of the flow with HTTP listener component.
- API ID for the Autodiscovery configuration should be externalized into property files 
- API ID Property for the Autodiscovery should be unique for each environments, unless it is a set of defined values (-1, 0, 1), since these values can be injected at deployment time without storing it in property files
- All HTTP Listeners have an auto discovery assigned (optional, default to on). It is set to _optional_ for the scenario when  some endpoints need to be managed without API Autodiscovery.
- There should be no unused Autodiscovery configuration.

**Comment by adesjardin** [comment]
To implement this rule we will do the following:

- Find all auto discovery elements
- Find all flows with http listener sources.
- Verify that all auto discovery elements reference a valid flow w/ http listener source and there are no duplicate references
- Verify that all flows w/ http listener sources are referenced from an auto discovery element
- Verify that all auto discovery elements reference the apiId using a property ${propertyName}
- Look up the apiId property in each environment property file to make sure it exists and is set to a dummy value (-1,0,1) to be overwritten at deployment time, or that each environment has a unique value.

**Comment by dileepkumarv-avio** [comment]
AUTO_DISCOVERY_EXISTS linter rule has been implemented to check for Autodiscovery configuration in Mule application. Implementation in done in PR - [#130 ](https://github.com/avioconsulting/mule-linter/pull/130)
